version: "3"
services:
  rmqnamesrv:
    image: apacherocketmq/rocketmq:4.5.0
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    volumes:
      - ../logs/rocketmq/logs:/home/rocketmq/logs
    command: sh mqnamesrv
    networks:
      - pika-net

  rmqbroker:
    image: apacherocketmq/rocketmq:4.5.0
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    volumes:
      - ../logs/rocketmq/logs:/home/rocketmq/logs
      - ../data/rocketmq/store:/home/rocketmq/store
      - ./conf/rocketmq/broker.conf:/home/rocketmq/rocketmq-4.5.0/conf/broker.conf
    command: sh mqbroker -n rmqnamesrv:9876 -c ../conf/broker.conf
    environment:
      - JAVA_HOME=/usr/lib/jvm/jre
      - Dcom.rocketmq.sendMessageWithVIPChannel=true
    depends_on:
      - rmqnamesrv
    networks:
      - pika-net

  rmqadmin:
    image: pangliang/rocketmq-console-ng
    container_name: rmqadmin
    ports:
      # 9000供外部控制台访问界面使用
      - 9000:8080
    environment:
      JAVA_OPTS: "-Drocketmq.namesrv.addr=rmqnamesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=true"
    depends_on:
      - rmqnamesrv
    networks:
      - pika-net