version: "3"
services:
  # 分布式事务服务
  seata-server:
    image: seataio/seata-server:1.3.0
    container_name: seata-server
    ports:
      - "8091:8091"
    links:
      - mysql
      - nacos
    depends_on:
      - mysql
      - nacos
    environment:
      - SEATA_PORT=8091
      - STORE_MODE=db
    volumes:
      - "./conf/seata/registry.conf:/seata-server/resources/registry.conf"
      - "../logs/seata:/root/logs/seata"
    networks:
      - pika-net