server:
  port: 8120
spring:
  # 数据库
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATASOURCE_HOST:127.0.0.1}:3306/pika_upms?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=GMT%2b8
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:123456}
    # 数据库连接池
    druid:
      filters: stat
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
      maxActive: 20
      initialSize: 5
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      # Druid StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin
        allow:
        deny:
      # Druid WebStatFilter配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: .js,*.gif,*.png,*.jpg,*.html,*.js,*.css,*.ico,/druid/*
  cloud:
    sentinel:
      transport:
        dashboard: ${SENTINEL_DASHBOARD_HOST:127.0.0.1}:${SENTINEL_DASHBOARD_PORT:8858}
        port: ${SENTINEL_PORT:8719}
      datasource:
        ds1:
          # 将限流规则持久化进nacos配置中心
          nacos:
            server-addr: ${REGISTER_HOST:127.0.0.1}:${REGISTER_PORT:8848}
            dataId: pika-upms-sentinel
            groupId: PIKA
            data-type: json
            rule-type: flow
            username: ${REGISTER_USERNAME:nacos}
            password: ${REGISTER_PASSWORD:nacos}
    # 分布式消息
    stream:
      rocketmq:
        binder:
          name-server: ${ROCKET_MQ_HOST:127.0.0.1}:${ROCKET_MQ_PORT:9876}

    # 消息总线
    bus:
      id: ${spring.application.name}:${server.port}
      trace:
        enabled: true
      destination: springCloudBus

# mybatis-plus
mybatis-plus:
  # config-location:
  mapper-locations: classpath:mapper/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.wenlincheng.pika.upms.entity.po
  configuration:
    # 驼峰下划线转换
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
  global-config:
    banner: false
    # 数据库大写下划线转换
    #capital-mode: true
    # 序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    # 数据库相关配置
    db-config:
      # 主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: ASSIGN_ID
      capital-mode: true
      # 逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0

# 代码生成
gen:
  # 项目名
  serverName: ${spring.application.name}
  # 自定义包路径
  packagePath: com.wenlincheng.pika
  # 包名
  packageName: upms
  # 数据库表名
  tableNames:
    - sys_logs
  # 设置作者
  author: Pikaman
  # 数据库
  database:
    url: ${spring.datasource.druid.url}
    username: ${spring.datasource.druid.username}
    password: ${spring.cloud.nacos.config.password}